### ISSUE TITLE
Highlight current day

### ISSUE THREAD

**Issue by eseglem** [big-beat/bigbeat.io#1]
Highlight the current day for convenience. Maybe slightly darken past days in current period?

**Comment by jrib** [comment]
@eseglem 

#4 hides the context days so it's less confusing when we lighten the past/before-today days.

Not sure if light and dark mode both look ok.

Not doing anything special for today other than the old bold font weight.

Thoughts?

**Comment by eseglem** [comment]
Doesn't seem to actually Highlight today, just dulls previous days. But it is handy still.

**Comment by jrib** [comment]
yeah, the bold is too subtle at the moment for the "today" styling for sure

**Comment by jrib** [comment]
Alright, added a border around today... a little easier to see
