### ISSUE TITLE
Add sprint start / end

### ISSUE THREAD

**Issue by eseglem** [big-beat/bigbeat.io#2]
Add the sprint start and end dates to the calendar. Mostly corresponds to off Fridays, but can differ with holidays. 

A circle and square or stop sign in same color as dates in the bottom right corner of the square could work and still stay pretty minimal.

**Comment by jrib** [comment]
I feel like this would make it to busy without much benefit since the blue fridays already correspond to sprint, but if you come up with something that looks good I'd reconsider!

**Comment by eseglem** [comment]
Yeah, I agree it would be a bit busy. I think a small icon wouldn't be horrible. But not a lot of gain there as long as you train your brain with it. Just knowing that today is a sprint start without having to look at other days could maybe be of value.
